on:
  workflow_dispatch:
        

env:
  TARGET_RUBY_VER: ${{ inputs.target_ruby_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          path: build   



      - name: Prepare build environment
        run: |
          echo "This is a test"
        
        shell: bash